# Generated by Django 2.1.3 on 2018-11-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Hình ảnh')),
                ('is_homepage_content', models.BooleanField(default=True, verbose_name='Hiển thị ở mục giới thiệu ?')),
                ('code', models.SlugField(max_length=100, verbose_name='Mã danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục cấp 2',
                'verbose_name_plural': 'Danh mục cấp 2',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('cate_type', models.CharField(choices=[('0', 'Dịch vụ'), ('1', 'Sản phẩm')], max_length=20, verbose_name='Loại danh mục')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='category_images', verbose_name='Hình ảnh')),
                ('is_homepage_content', models.BooleanField(default=True, verbose_name='Hiển thị ở mục giới thiệu ?')),
                ('column_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='Số cột hiển thị')),
                ('code', models.SlugField(max_length=100, verbose_name='Mã danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục cấp 1',
                'verbose_name_plural': 'Danh mục cấp 1',
            },
        ),
        migrations.AddField(
            model_name='detailsubcategory',
            name='parent_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movento_web_app.SubCategory', verbose_name='Danh mục cha'),
        ),
    ]
