# Generated by Django 2.1.3 on 2018-11-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movento_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nội dung')),
                ('page', models.CharField(choices=[('0', 'Trang chủ'), ('1', 'Giới thiệu'), ('2', 'Danh mục cấp 2')], max_length=20, verbose_name='Trang')),
                ('component_type', models.CharField(choices=[('0', 'Cover'), ('1', 'Slide ảnh giới thiệu'), ('2', 'Dịch vụ cung cấp'), ('3', 'Công trình tiêu biểu'), ('4', 'Nhận xét khách hàng'), ('5', 'Call to action'), ('6', 'Quảng cáo')], max_length=20, verbose_name='Bộ phận')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Nội dung trang',
                'verbose_name_plural': 'Nội dung trang',
            },
        ),
        migrations.CreateModel(
            name='ContentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images', verbose_name='Hình ảnh')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movento_web_app.Content', verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Hình ảnh nội dung',
                'verbose_name_plural': 'Hình ảnh nội dung',
            },
        ),
    ]
