# Generated by Django 2.1.3 on 2018-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movento_web_app', '0004_detailpost_detailpostimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đối tác')),
                ('web', models.URLField(blank=True, verbose_name='Link web')),
                ('image', models.ImageField(upload_to='partner_images', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
            },
        ),
    ]
