# Generated by Django 2.1.3 on 2018-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movento_web_app', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('image', models.ImageField(upload_to='content_images', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
            ],
            options={
                'verbose_name': 'Nhận xét khách hàng',
                'verbose_name_plural': 'Nhận xét khách hàng',
            },
        ),
    ]
