# Generated by Django 2.1.3 on 2018-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movento_web_app', '0006_customercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Tên công ty')),
                ('tel', models.CharField(max_length=100, verbose_name='Tel')),
                ('mobile', models.CharField(max_length=100, verbose_name='Mobile')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('showroom', models.TextField(verbose_name='Showroom & office')),
                ('factory', models.TextField(verbose_name='Xưởng')),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
    ]
